import { NextResponse } from 'next/server';
import { supabaseServerClient } from '@/lib/supabase/server';

// Tool seed data (id will be auto-generated by Supabase)
const SEED_TOOLS = [
  // Image & Design
  {
    name: 'Midjourney',
    affiliate_url: 'https://www.midjourney.com',
    desc_en: 'Premium-quality image generation with the most stable results. The default choice for many creators.',
    desc_simple_en: 'AI art generation with premium quality',
    task_category: 'image',
    best_for: 'Art & Concept Design',
    tags: ['Art', 'High Quality', 'Popular'],
    manual_rank: 1,
    rank_in_task: 1,
    why_pick: 'Chosen for consistently stable output and the largest creator community',
  },
  {
    name: 'Leonardo AI',
    affiliate_url: 'https://leonardo.ai',
    desc_en: 'Great for concept art and game assets with lots of presets and templates to start from.',
    desc_simple_en: 'AI-powered image generation for game assets and concept art',
    task_category: 'image',
    best_for: 'Game Assets & Concept Art',
    tags: ['Game Assets', 'Concept Art', 'High Quality'],
    manual_rank: 2,
    rank_in_task: 2,
    why_pick: 'Chosen for best price-to-quality ratio with extensive template library',
  },
  {
    name: 'Canva',
    affiliate_url: 'https://www.canva.com',
    desc_en: 'Template-based design tool that makes thumbnails and posters easy, even if you\'re not a designer.',
    desc_simple_en: 'Beginner-friendly design tool with AI-powered templates',
    task_category: 'image',
    best_for: 'Social Media & Templates',
    tags: ['Beginner Friendly', 'Templates', 'All-in-one'],
    manual_rank: 3,
    rank_in_task: 3,
    why_pick: 'Chosen for zero learning curve and instant professional results',
  },
  // Writing
  {
    name: 'ChatGPT',
    affiliate_url: 'https://chat.openai.com',
    desc_en: 'General-purpose writer for emails, essays, resumes, blog posts and more.',
    desc_simple_en: 'AI writing assistant for all purposes',
    task_category: 'writing',
    best_for: 'All Writing Tasks',
    tags: ['Writing', 'Versatile', 'Popular'],
    manual_rank: 1,
    rank_in_task: 1,
    why_pick: 'Chosen for proven versatility across all writing tasks by millions',
  },
  {
    name: 'Claude',
    affiliate_url: 'https://claude.ai',
    desc_en: 'Strong at long reports and structured documents with clear, logical reasoning.',
    desc_simple_en: 'AI assistant for long-form writing',
    task_category: 'writing',
    best_for: 'Long-form Content',
    tags: ['Long-form', 'Reports', 'Analysis'],
    manual_rank: 2,
    rank_in_task: 2,
    why_pick: 'Chosen for superior long-form reasoning at competitive pricing',
  },
  {
    name: 'Notion AI',
    affiliate_url: 'https://www.notion.so/product/ai',
    desc_en: 'Helps you draft, summarize and reorganize notes directly inside your Notion workspace.',
    desc_simple_en: 'AI writing integrated in Notion',
    task_category: 'writing',
    best_for: 'Workspace Integration',
    tags: ['Notion', 'Notes', 'Integration'],
    manual_rank: 3,
    rank_in_task: 3,
    why_pick: 'Chosen for seamless integration with existing workflow',
  },
  // Video
  {
    name: 'Runway',
    affiliate_url: 'https://runwayml.com',
    desc_en: 'All-in-one video creation and editing. Widely used for shorts and YouTube content.',
    desc_simple_en: 'AI video editing and generation',
    task_category: 'video',
    best_for: 'Video Creation',
    tags: ['Video', 'Editing', 'AI Generation'],
    manual_rank: 1,
    rank_in_task: 1,
    why_pick: 'Chosen by professional creators for industry-leading quality',
  },
  {
    name: 'Pika',
    affiliate_url: 'https://pika.art',
    desc_en: 'Good for quick, fun clips and meme-style short videos with simple controls.',
    desc_simple_en: 'Fast AI video generation',
    task_category: 'video',
    best_for: 'Quick Clips',
    tags: ['Fast', 'Short Videos', 'Memes'],
    manual_rank: 2,
    rank_in_task: 2,
    why_pick: 'Chosen for fastest turnaround on viral-style content creation',
  },
  {
    name: 'CapCut',
    affiliate_url: 'https://www.capcut.com',
    desc_en: 'Free editor with built-in AI features. Great for subtitles and detailed timeline edits.',
    desc_simple_en: 'Free AI video editor',
    task_category: 'video',
    best_for: 'Video Editing',
    tags: ['Free', 'Editing', 'Subtitles'],
    manual_rank: 3,
    rank_in_task: 3,
    why_pick: 'Chosen for free access to professional editing features',
  },
  // Audio
  {
    name: 'Suno',
    affiliate_url: 'https://suno.ai',
    desc_en: 'End-to-end AI music generation – lyrics and full tracks for BGM or personal projects.',
    desc_simple_en: 'AI music generation with lyrics',
    task_category: 'audio',
    best_for: 'Music Creation',
    tags: ['Music', 'Lyrics', 'Full Tracks'],
    manual_rank: 1,
    rank_in_task: 1,
    why_pick: 'Chosen for most advanced full-track generation by music creators',
  },
  {
    name: 'Udio',
    affiliate_url: 'https://udio.com',
    desc_en: 'Another strong AI music option when you want slightly different styles and flavors.',
    desc_simple_en: 'AI music with unique styles',
    task_category: 'audio',
    best_for: 'Music Variety',
    tags: ['Music', 'Styles', 'Alternative'],
    manual_rank: 2,
    rank_in_task: 2,
    why_pick: 'Chosen for competitive quality with unique style variations',
  },
  {
    name: 'AIVA',
    affiliate_url: 'https://www.aiva.ai',
    desc_en: 'Focused on cinematic and classical-style background music for games and film.',
    desc_simple_en: 'AI cinematic music composer',
    task_category: 'audio',
    best_for: 'Cinematic Music',
    tags: ['Cinematic', 'Classical', 'Games'],
    manual_rank: 3,
    rank_in_task: 3,
    why_pick: 'Chosen for easy cinematic and game soundtrack creation',
  },
  // Voice
  {
    name: 'ElevenLabs',
    affiliate_url: 'https://elevenlabs.io',
    desc_en: 'One of the most natural-sounding TTS engines for dubbing, narration and character voices.',
    desc_simple_en: 'Natural AI voice generation',
    task_category: 'voice',
    best_for: 'Voice Synthesis',
    tags: ['TTS', 'Natural', 'Dubbing'],
    manual_rank: 1,
    rank_in_task: 1,
    why_pick: 'Chosen for most natural voice quality by content creators worldwide',
  },
  {
    name: 'HeyGen',
    affiliate_url: 'https://www.heygen.com',
    desc_en: 'Generates talking-head avatar videos with synced lips and translated speech.',
    desc_simple_en: 'AI avatar video generation',
    task_category: 'voice',
    best_for: 'Avatar Videos',
    tags: ['Avatar', 'Lip Sync', 'Translation'],
    manual_rank: 2,
    rank_in_task: 2,
    why_pick: 'Chosen for complete avatar video solution at competitive price',
  },
  {
    name: 'Play.ht',
    affiliate_url: 'https://play.ht',
    desc_en: 'Large collection of multilingual voice presets, useful for international content.',
    desc_simple_en: 'Multilingual AI voice',
    task_category: 'voice',
    best_for: 'Multilingual TTS',
    tags: ['Multilingual', 'TTS', 'International'],
    manual_rank: 3,
    rank_in_task: 3,
    why_pick: 'Chosen for best multilingual support for global audiences',
  },
  // Coding
  {
    name: 'GitHub Copilot',
    affiliate_url: 'https://github.com/features/copilot',
    desc_en: 'Inline AI code suggestions directly in your IDE, great for everyday development.',
    desc_simple_en: 'AI code completion in IDE',
    task_category: 'coding',
    best_for: 'Code Completion',
    tags: ['IDE', 'Coding', 'Productivity'],
    manual_rank: 1,
    rank_in_task: 1,
    why_pick: 'Chosen by professional developers for proven productivity gains',
  },
  {
    name: 'Cursor',
    affiliate_url: 'https://cursor.sh',
    desc_en: 'AI-powered editor based on VS Code that understands your project and assists with refactors.',
    desc_simple_en: 'AI-powered code editor',
    task_category: 'coding',
    best_for: 'Full IDE',
    tags: ['Editor', 'VS Code', 'Refactoring'],
    manual_rank: 2,
    rank_in_task: 2,
    why_pick: 'Chosen for full IDE with superior project understanding',
  },
  {
    name: 'Replit Ghostwriter',
    affiliate_url: 'https://replit.com/ai',
    desc_en: 'AI coding assistant built into the Replit browser IDE for quick experiments and learning.',
    desc_simple_en: 'Browser-based AI coding',
    task_category: 'coding',
    best_for: 'Web IDE',
    tags: ['Browser', 'Learning', 'Quick'],
    manual_rank: 3,
    rank_in_task: 3,
    why_pick: 'Chosen for zero-setup learning and rapid prototyping',
  },
];

export async function GET() {
  try {
    const results = [];

    for (const tool of SEED_TOOLS) {
      // Check if tool already exists by name
      const { data: existing } = await supabaseServerClient
        .from('tools')
        .select('id, name')
        .eq('name', tool.name)
        .single();

      if (existing) {
        // Update existing tool
        const { error: updateError } = await supabaseServerClient
          .from('tools')
          .update({
            affiliate_url: tool.affiliate_url,
            desc_en: tool.desc_en,
            desc_simple_en: tool.desc_simple_en,
            task_category: tool.task_category,
            best_for: tool.best_for,
            tags: tool.tags,
            manual_rank: tool.manual_rank,
            rank_in_task: tool.rank_in_task,
            why_pick: tool.why_pick,
          })
          .eq('id', existing.id);

        if (updateError) {
          results.push({ name: tool.name, status: 'error', error: updateError.message });
        } else {
          results.push({ name: tool.name, status: 'updated' });
        }
      } else {
        // Insert new tool
        const { error: insertError } = await supabaseServerClient
          .from('tools')
          .insert(tool);

        if (insertError) {
          results.push({ name: tool.name, status: 'error', error: insertError.message });
        } else {
          results.push({ name: tool.name, status: 'inserted' });
        }
      }
    }

    return NextResponse.json({
      message: 'Tool seed completed',
      results,
    });
  } catch (error) {
    console.error('Tool seed error:', error);
    return NextResponse.json(
      { error: 'Failed to seed tools' },
      { status: 500 }
    );
  }
}

